### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#10]
Home Screen of the app.
When user either open the app and if they already Sign in then they will see this screen

![image](https://user-images.githubusercontent.com/59083528/125868393-ced8d9a8-7832-49e1-951b-e81da47734ae.png)

**Comment by Vedsaga** [comment]
@Sargam-Agarwal if screen are completed could you please rise the PR, then @imssurya anna can review it..

**Comment by Vedsaga** [comment]
@Sargam-Agarwal are you working on this? If yes do you required any help? If no, have you completed it?

**Comment by Sargam-Agarwal** [comment]
Hey @Vedsaga,
I have to just create the PR. Most of it is done, somethings are left which Im not able to complete right now coz my oncampus internships have almost started. 
I have been coordinating with Surya about it btw. Ill create the PR as soon as I get time.

**Comment by Vedsaga** [comment]
Minor changes in Top Bar and Navigation Bar Design.
![Screenshot_20210809_133755](https://user-images.githubusercontent.com/59083528/128676564-2fce02cc-e28c-4b92-ab9c-6f850fd127c5.jpg)

![Screenshot_20210809_133800](https://user-images.githubusercontent.com/59083528/128676569-f29d0290-76de-4503-9654-f30af67b877a.jpg)
