### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#2]
First Screen when user open app for first instance.

![image](https://user-images.githubusercontent.com/59083528/125867400-323cf612-445d-41d2-8633-e13fcf94ff69.png)

**Comment by rexdivakar** [comment]
@arun-muralidharan @imssurya  Don;'t close the issue until @Vedsaga validates and approves the changes.

**Comment by Vedsaga** [comment]
![Screenshot_20210717_123358](https://user-images.githubusercontent.com/59083528/126029150-f434eb6f-d3a7-4f80-90ee-a22924f66dd0.jpg)
 
@arun-muralidharan  Everything looks good. Can you please just replace the logo file from .png to  .svg

Thanks

**Comment by arun-muralidharan** [comment]
Flutter doesn't have native svg support; but I think there is a package. I'll get to it.
