### ISSUE TITLE
View Supplier

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#39]
In the first screen user will be able to see all the listed suppliers which was added earlier.
![Screenshot_20210730_132538](https://user-images.githubusercontent.com/59083528/127624748-b5ac55c9-30a0-4f87-9155-b58987cf2cd9.jpg)

To view detail information related to specific supplier, user can click on any of the supplier and then they can see all the details.

![Screenshot_20210730_132605](https://user-images.githubusercontent.com/59083528/127624768-90f4d186-fef8-4457-8c7f-0a4e9a097f59.jpg)

**Comment by Vedsaga** [comment]
Just some UI changes.. Like `Button` and it's color... All these changes will be applicable accross the Listing Component
![IMG_20210731_140706](https://user-images.githubusercontent.com/59083528/127734267-819f980b-9cf7-49d5-b5ac-e1989a993209.jpg)
![IMG_20210731_140013](https://user-images.githubusercontent.com/59083528/127734268-f486c69d-0520-4317-8137-179be38c038c.jpg)
![IMG_20210731_135946](https://user-images.githubusercontent.com/59083528/127734269-d4eeddc6-6983-4982-b807-cc860638e494.jpg)
![IMG_20210731_135934](https://user-images.githubusercontent.com/59083528/127734274-2202a17b-01de-4cc9-8068-c2ec6aac70b7.jpg)

**Comment by Vedsaga** [comment]
Slight change in UI for view Supplier, `Top Bar have been romoved`... 
Attaching user Interaction screen recording for future reference... 

https://user-images.githubusercontent.com/59083528/127759727-0961178f-4e31-474c-b15f-7a91bf1c7907.mp4

**Comment by Vedsaga** [comment]
Sorry, earlier I forgot to add Error Handling UI.

Attaching it below

Below error will once if user try to proceed with filling Supplier Phone number 
![Screenshot_20210803_050953](https://user-images.githubusercontent.com/59083528/127936513-eb76eeea-644e-4abb-b349-c4a76ce8c336.jpg)


Below error will once if user try to proceed with filling Supplier Address 

![Screenshot_20210803_051002](https://user-images.githubusercontent.com/59083528/127936580-f134353b-da62-4dc9-8d29-4595726f52eb.jpg)


Below error will occur if user try to add Supplier which already exist.
![Screenshot_20210803_050958](https://user-images.githubusercontent.com/59083528/127936628-a1b6b9dc-75f8-4b05-a9b1-684393a7b925.jpg)


These are the possible scenarios where Error can occur during `Adding Supplier`

**Comment by Vedsaga** [comment]
I just saw that button all buttons in listing components were black-color so, I only changed the buttons color to blue, @arun-muralidharan anna hoping that these changes in the Button color will not hamper the work flow. These `buttons` will remaining consistently  through out the app. 

![IMG_20210803_135725](https://user-images.githubusercontent.com/59083528/127984125-8b485035-8c10-4413-968e-30f356d49213.jpg)
![IMG_20210803_135655](https://user-images.githubusercontent.com/59083528/127984148-28225556-b705-4e22-a13d-0a5de425598e.jpg)
![IMG_20210803_135624](https://user-images.githubusercontent.com/59083528/127984154-d194e942-e312-400a-8713-ba4ffeffe78c.jpg)

**Comment by arun-muralidharan** [comment]
This shouldn't be a problem; I'll make the changes.

**Comment by Vedsaga** [comment]
Anna once I click on the `supplier` button  it doesn't proceed to next screen. It's stuck here.. Can you please check 


https://user-images.githubusercontent.com/59083528/128022459-7bfeed93-54bc-44aa-97a9-3ca42468a552.mp4

**Comment by Vedsaga** [comment]
I got the reason why it's happening, it is because there is no Supplier added via my account. Can we just show them just blank screen instead of this process animation

**Comment by Vedsaga** [comment]
Ohh yaa Anna  right pointed out, Post Sign-In Supplier is yet to be completed... @imssurya anna #24   is it ready?

**Comment by Vedsaga** [comment]
Anna just once small fix.. Could we change `+` black to blue color.. 

![Screenshot_20210803_185822](https://user-images.githubusercontent.com/59083528/128023604-c7aa8d84-5761-44fc-b1bc-4972f199553f.jpg)

**Comment by arun-muralidharan** [comment]
> Anna just once small fix.. Could we change `+` black to blue color..

Yes, I'll make the change.

**Comment by Vedsaga** [comment]
@arun-muralidharan Anna do we plan to change the UI for view Supplier? Yesterday, I didn't noticed it.. 

`Current this is how it looks in Flutter`

![Screenshot_20210804_062643](https://user-images.githubusercontent.com/59083528/128105061-71c8677e-2f87-4a8b-aed3-5288d6b83613.jpg)


However it would be nice if looks like this
 `New UI`
![Screenshot_20210804_062515](https://user-images.githubusercontent.com/59083528/128104893-1760d715-42da-4923-80c0-de4c90f8a82b.jpg)

**Comment by arun-muralidharan** [comment]
Oh, sorry! I was experimenting with dynamic tiling and I forgot to revert it. So, it changes layout depending on the width of the screen. I'll edit it today.

**Comment by Vedsaga** [comment]
No worries Anna 😊, please don't say sorry 👍
