### ISSUE TITLE
Subscription for owner

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#4]
During Owner Sign-up owner can activate there account.

![image](https://user-images.githubusercontent.com/59083528/125867855-d89ba8ba-a443-4b26-ac21-cfe3f1cd6ce3.png)

**Comment by Vedsaga** [comment]
Now, as we know their is not separate steps during Sign-UP except filling details verifying mail. This is why this issue is also  getting close because now. Now subscription is only for owner account so this step fall under **Post Sign-in** issue.

**Comment by rexdivakar** [comment]
Hey @Vedsaga the username filed will be updated by flutter from backend which wont be an input field for the user so u can remove it from the design

**Comment by Vedsaga** [comment]
@rexdivakar anna we have already this subscription step followed by Owner Screen. So, that's why I closed this issues and added Subscription step into #24

**Comment by Vedsaga** [comment]
Reopening the subscription Issue because, **owner** can't Sign-IN if thier account is not subscribed. And, if owner account is not subscribed and they try to Sign-in then they will see the error screen attached below. 

![Screenshot_20210728_094426](https://user-images.githubusercontent.com/59083528/127263038-37f584c2-b6eb-47a8-b6a8-1a63251b495f.jpg)


Once user clicks on Subscribe button then we will move them to **Fill Activation Key** screen screen shot attached below. 

![Screenshot_20210728_090907](https://user-images.githubusercontent.com/59083528/127263293-abaad3fa-fc37-4f3d-9e90-9bf7e2020c28.jpg)



Once they fill the activation key and click on Activate then we will show them successful screen if activation key which they provide is correct. Screen shot attached below. 

![Screenshot_20210728_095359](https://user-images.githubusercontent.com/59083528/127263439-b7dea579-8bd3-4aa7-a7a8-d26a002b011c.jpg)


Incase if they provided wrong activation key then we will show them Error. Screenshort attached below. 
![Screenshot_20210728_095513](https://user-images.githubusercontent.com/59083528/127263520-f8fb42b8-5510-4c82-ba4f-a69d203519e4.jpg)
