### ISSUE TITLE
Edit Supplier

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#41]
Current we will allow user to only edit descriptions filed, except that they cannot access any other fields.

![Screenshot_20210730_132723](https://user-images.githubusercontent.com/59083528/127627059-51b40823-f9d0-4f57-a45c-f249430e4d43.jpg)

Once they click on `confim ` we will ask them for confirmation says they are trying to change the details
![Screenshot_20210730_132740](https://user-images.githubusercontent.com/59083528/127627145-f5d5ff9c-88d7-450e-b3ab-9b5a1fd506b2.jpg)

Once user clicks on save we will show them confirmation screen if they click on discard then we will take them back to edit screen. 
![Screenshot_20210730_132711](https://user-images.githubusercontent.com/59083528/127627322-fb05dd19-d808-4a18-802f-e8f158882ec5.jpg)

Once user clicks on `Go back to Supplier` Button  we will take them to View Supplier Screen.

**Comment by Vedsaga** [comment]
I attached Wrong Confirmation UI screen, so I am correcting it here. 
![Screenshot_20210730_142233](https://user-images.githubusercontent.com/59083528/127628169-fe588f35-1777-4204-b4a6-52cd04b03e0f.jpg)

**Comment by Vedsaga** [comment]
Slight change in UI from perivous Edit New Supplier UI. At the top of the bar `Supplier Details` is added to highlight which screen users are currently in.. Also, back button is bit smaller. Screen recording is attached of user interaction for future reference.

https://user-images.githubusercontent.com/59083528/127759873-c80192d5-7bb3-49ea-98ab-3bac309e3681.mp4

**Comment by Vedsaga** [comment]
Just a small UI bug, so if user try to edit the description and then then decide to cancel the description still remains visible in the UI till user does not click on back button. Also, when user again clicks on edit button the same text which he filled while last attempt remained store. It would be nice we just fix this.



https://user-images.githubusercontent.com/59083528/128355300-716518f9-f424-47d8-87dc-7d4c944f5de5.mp4

**Comment by Vedsaga** [comment]
Anna can we also fix this in UI... 
![IMG_20210805_185557](https://user-images.githubusercolist t.com/59083528/128357590-ce61b5b7-0f97-4816-9841-926fa2588e8a.jpg)


So, when the list is more certain point where it can't fit on the screen then it is just showing them blank white card.. There is no issue with data or anything just only UI when I scroll down all is working perfectly.. 


https://user-images.githubusercontent.com/59083528/128357784-cabfcf62-3965-45d5-8d56-f173d42636e6.mp4

**Comment by arun-muralidharan** [comment]
Will fix these issues.
