### ISSUE TITLE
Common Sign-UP Error

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#5]
While user Sign-Up these error will occur
![image](https://user-images.githubusercontent.com/59083528/125867986-f65a5266-e6e1-4535-a4e0-92bd75a6e58f.png)

**Comment by arun-muralidharan** [comment]
@rexdivakar What is the bug in error? Is it not showing certain errors when it should?

**Comment by Vedsaga** [comment]
@arun-muralidharan @rexdivakar Anna were just giving me demo that, if you find any bug while testing apk you can just change lable type. The main concern was just redirecting after Sign-up. I believe you have already mentioned that it's fixed so, there is nothing much...

**Comment by Vedsaga** [comment]
@arun-muralidharan Completed error message is not visible. Can you please just fix that. Rest all the error is perfectly working. Once this is fixed we can close this issue. 


![IMG_20210723_142708](https://user-images.githubusercontent.com/59083528/126759644-1e3b7062-5785-48bd-a345-3f7f00a819f1.jpg)

**Comment by Vedsaga** [comment]
All types of  **Errors Handling** is being completed. Everything is working perfectly.
