### ISSUE TITLE
Restricting Worker access 

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#62]
It would be nice if we just completely disable/hide the call for action button (`Add`,  `Edit` and `Remove`) for worker through out all the 6 listing components.
![IMG_20210805_102400](https://user-images.githubusercontent.com/59083528/128292994-cc692669-a09e-40a0-b788-7abcadfb207a.jpg)

![IMG_20210805_102439](https://user-images.githubusercontent.com/59083528/128292985-81953a37-bd73-4b55-a81b-4a19b846219d.jpg)

**Comment by Vedsaga** [comment]
@arun-muralidharan Anna is this possible to implement? Can we restrict/ hide the features from a user  based on there user-type while we can have access to theuer user type from backend? I just just created another issue #66 which only user-type `owner` supposed to access.

**Comment by arun-muralidharan** [comment]
> @arun-muralidharan Anna is this possible to implement? Can we restrict/ hide the features from a user based on there user-type while we can have access to theuer user type from backend? I just just created another issue #66 which only user-type `owner` supposed to access.

Yes, this is possible. We can add the user type to the authentication state and use it to show/hide. I'll implement this along with #42

**Comment by Vedsaga** [comment]
Just confirming with backend team, because I earlier forget to made UI... ASA I get confirmation I will create other issues accordingly..
