### ISSUE TITLE
Sign in Screen

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#7]
Sign-in screen for both worker and owner.

![image](https://user-images.githubusercontent.com/59083528/125868208-db8d7646-353a-472f-b39d-4bd311db6220.png)

**Comment by Vedsaga** [comment]
As Sign-up is partially completed, we can work on Sign-in part.

**Comment by Vedsaga** [comment]
@arun-muralidharan one request so, from next time while submitting PR if it would be nice if you can tag the issue with that PR, in future incase of any problem we can know it. For time being I am manually tag all the closed issues with accepted PR.

**Comment by arun-muralidharan** [comment]
@Vedsaga I mention the issue in the PR. From now on, I'll also tag the PR in the issue.

**Comment by Vedsaga** [comment]
Slight change in Sign-in UI. 

![Screenshot_20210724_132459](https://user-images.githubusercontent.com/59083528/126862152-420efcc1-3c98-4bf0-9521-dab80c47790b.jpg)

![Screenshot_20210724_132504](https://user-images.githubusercontent.com/59083528/126862162-b7155db9-609a-447a-9fc7-71d3b1bce70d.jpg)

**Comment by arun-muralidharan** [comment]
#30 & #31 

@Vedsaga After these merges sign in should work for valid credentials, and show corresponding errors otherwise. There are no checks implemented yet to see if the email and/or is active. They will be added to sign in module after those modules are complete.

**Comment by Vedsaga** [comment]
> #30 & #31
> 
> @Vedsaga After these merges sign in should work for valid credentials, and show corresponding errors otherwise. There are no checks implemented yet to see if the email and/or account is active. They will be added to sign in module after those modules are complete.

Great, Once PR is request is accepted  by @imssurya , I will test the APK and if all worked then I will close this issue

**Comment by Vedsaga** [comment]
I just tested the Latest Apk version and sign for vaild credentials is working fine.. We are making quite a lot of progress.. great job team @imssurya @arun-muralidharan Anna 🙂

**Comment by Vedsaga** [comment]
@arun-muralidharan Anna there seems to bug somewhere..

When I am trying with
 username : `harshit` it's working 
User type : `Owner`

However when I am trying with
username : `harshit_worker` it's not giving any response 
User type : `worker`

I am attaching screen recording  please could you check, this also happen yesterday then I thought it could be due to my internet connection however it again happen today.  Also, yesterday I was using different apk and today I am today apk after Surya Anna accepted the PR. 

https://user-images.githubusercontent.com/59083528/128291763-19bc4084-557a-4dd6-bc59-0b0207c57c9f.mp4

**Comment by Vedsaga** [comment]
In this screen recording 

`harahit` is a valid username in that case its does respond with `Please enter valid credentials`

However `harsh ` is invalid username and in that case it does not respond with anything

https://user-images.githubusercontent.com/59083528/128294855-e0fe056e-302c-4f63-9f0a-fa7bf5b2ea69.mp4

After making few attempts I guess Error Handling is being not implemented, for `Wrong User`(username doesn't exist in db) is not implemented

**Comment by arun-muralidharan** [comment]
> After making few attempts I guess Error Handling is being not implemented, for `Wrong User`(username doesn't exist in db) is not implemented

This is because `/account_status/` returns '500 - Internal Server Error' for unknown username. I have notified backend about this; once it is fixed, this should be fixed as well. We can re-test it then just to be sure.

**Comment by Vedsaga** [comment]
Ohh, I guess it's fixed just not deployed... So, I will close this issue now.. If after deployment it's not fixed then we can reopen it.
