### ISSUE TITLE
Common Sign In error

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#9]
This error error will occur while both type of user try to login

Incase Wrong Email
Incase of Wrong Password
Missing key-value argument(s)

![image](https://user-images.githubusercontent.com/59083528/125868333-a5ccb20d-5157-4322-9f64-8a427c114669.png)

**Comment by Vedsaga** [comment]
**As email Verification is deployed so, in case while Sign-up user don't verify thier mail and then try to Sign-in then we will show them this error screen :**

![Screenshot_20210724_133858](https://user-images.githubusercontent.com/59083528/126862323-2e897680-3d53-4b9a-ba31-d42cad645052.jpg)

Once user clicked on **Verify button** then we  will show them Enter OTP screen or user can click on the link which is attached to thier email and we will redirect to email confirmation screen. The whole procuder once user click on verify button is similar steps followed in issue no. #3 (Sign-up) 


Also, as there is Slight change in Sign-in UI. That why also there is some changes in Sign-in Error UI. 

Error Message : `Please Enter User & Password! `
![Screenshot_20210724_132514](https://user-images.githubusercontent.com/59083528/126862199-58b599c6-9ad6-4142-b646-3f460ef5b6a5.jpg)

Error Message : `Please Enter Vaild Credentials`
![Screenshot_20210724_132535](https://user-images.githubusercontent.com/59083528/126862263-ea100e7b-45f5-4e4d-8a35-bd29ae560f93.jpg)

**Comment by Vedsaga** [comment]
> **As email Verification is deployed so, in case while Sign-up user don't verify thier mail and then try to Sign-in then we will show them this error screen :**
> 
> ![Screenshot_20210724_133858](https://user-images.githubusercontent.com/59083528/126862323-2e897680-3d53-4b9a-ba31-d42cad645052.jpg)
> 
> Once user clicked on **Verify button** then we will show them Enter OTP screen or user can click on the link which is attached to thier email and we will redirect to email confirmation screen. The whole procuder once user click on verify button is similar steps followed in issue no. #3 (Sign-up)
> 
> Also, as there is Slight change in Sign-in UI. That why also there is some changes in Sign-in Error UI.
> 
> Error Message : `Please Enter User & Password! `
> ![Screenshot_20210724_132514](https://user-images.githubusercontent.com/59083528/126862199-58b599c6-9ad6-4142-b646-3f460ef5b6a5.jpg)
> 
> Error Message : `Please Enter Vaild Credentials`
> ![Screenshot_20210724_132535](https://user-images.githubusercontent.com/59083528/126862263-ea100e7b-45f5-4e4d-8a35-bd29ae560f93.jpg)

@imssurya @arun-muralidharan anna

**Redirecting user during Sign-in attempts incase if thier mail ID is not verified**  is it completed?

**Comment by arun-muralidharan** [comment]
@Vedsaga Not yet. We need to talk to backend before that can be implemented. For now, I'll work on the UI. Once we discuss with backend, we can implement it.

**Comment by Vedsaga** [comment]
All the issue is being handled. It seems except Resend OTP  every error is being handled and working fine.. For that exception case issue #37 is opened.
